# Generated by Django 4.2.7 on 2023-11-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Grade title', max_length=50, unique=True, verbose_name='Grade')),
            ],
            options={
                'verbose_name_plural': 'Grades',
                'ordering': ['title'],
            },
        ),
    ]
