# Generated by Django 4.2.7 on 2023-11-14 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entry_task__main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='grade',
            field=models.ForeignKey(help_text='Grade', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Entry_task__main.grade', verbose_name='Grade'),
        ),
    ]
