# Generated by Django 4.2.7 on 2023-11-14 19:44

import Entry_task__main.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry_task__main', '0002_alter_employee_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_employment',
            field=models.DateField(default=datetime.datetime.today, help_text='Date of employment', validators=[Entry_task__main.models.date_of_employment_validator], verbose_name='Date of employment'),
        ),
    ]
