# Generated by Django 4.2.7 on 2023-12-22 09:53

import Entry_task__main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry_task__main', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number must contain only 11 digits in format _(___)___-__-__', max_length=15, null=True, unique=True, validators=[Entry_task__main.models.validate_phone], verbose_name='Phone number'),
        ),
    ]
